interface Resource {
  name: string;
  title: string;
  description: string;
  resource: string;
  updated_at: string;
  callback: () => Promise<any>;
}

export const resources: Resource[] = [
  {
    name: "pratos-do-dia",
    title: "Pratos do Dia",
    description: "Pratos do Dia",
    resource: "menu://pratos-do-dia",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => [
      {
        id: 1,
        nome: "Bug-er Artesanal",
        descricao:
          "Hambúrguer 180g, queijo cheddar, bacon crocante, cebola caramelizada e molho especial da casa",
        preco: 32.9,
        categoria: "hamburgueres",
        tempo_preparo_minutos: 15,
        calorias: 850,
        restricoes: [],
        popular: true,
      },
      {
        id: 2,
        nome: "Wrap Deploy Rápido",
        descricao:
          "Wrap integral com frango grelhado, cream cheese, rúcula e tomate seco",
        preco: 26.9,
        categoria: "wraps",
        tempo_preparo_minutos: 8,
        calorias: 420,
        restricoes: [],
        popular: false,
      },
      {
        id: 3,
        nome: "Salada Código Limpo",
        descricao:
          "Mix de folhas, quinoa, grão de bico, cenoura ralada, pepino e molho tahine",
        preco: 28.9,
        categoria: "saladas",
        tempo_preparo_minutos: 5,
        calorias: 320,
        restricoes: ["vegano", "sem-gluten"],
        popular: true,
      },
      {
        id: 4,
        nome: "Macarrão Full Stack",
        descricao:
          "Espaguete ao molho pomodoro com almôndegas artesanais e parmesão",
        preco: 34.9,
        categoria: "massas",
        tempo_preparo_minutos: 18,
        calorias: 720,
        restricoes: [],
        popular: false,
      },
      {
        id: 5,
        nome: "Bowl Serverless",
        descricao:
          "Arroz integral, salmão grelhado, abacate, edamame, cenoura e molho ponzu",
        preco: 42.9,
        categoria: "bowls",
        tempo_preparo_minutos: 12,
        calorias: 580,
        restricoes: ["sem-gluten"],
        popular: true,
      },
      {
        id: 6,
        nome: "Pizza Quatro Commits",
        descricao:
          "Pizza individual com calabresa, mussarela, manjericão e azeitonas",
        preco: 38.9,
        categoria: "pizzas",
        tempo_preparo_minutos: 20,
        calorias: 890,
        restricoes: ["vegetariano"],
        popular: true,
      },
      {
        id: 7,
        nome: "Risoto Assíncrono",
        descricao: "Risoto de funghi com finalização de azeite trufado",
        preco: 45.9,
        categoria: "risotos",
        tempo_preparo_minutos: 25,
        calorias: 650,
        restricoes: ["vegetariano", "sem-gluten"],
        popular: false,
      },
      {
        id: 8,
        nome: "Filé Legacy",
        descricao:
          "Filé mignon grelhado com fritas rústicas e farofa de bacon. Clássico que nunca falha.",
        preco: 52.9,
        categoria: "carnes",
        tempo_preparo_minutos: 22,
        calorias: 980,
        restricoes: ["sem-gluten"],
        popular: true,
      },
    ],
  },
  {
    name: "bebidas",
    title: "Bebidas",
    description: "Bebidas",
    resource: "menu://bebidas",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => [
      {
        id: 101,
        nome: "Café Debug",
        descricao: "Espresso duplo pra resolver qualquer problema",
        preco: 8.9,
        categoria: "cafes",
        tamanho_ml: 60,
        temperatura: "quente",
        cafeina: true,
      },
      {
        id: 102,
        nome: "Café Latte Refactor",
        descricao: "Espresso com leite vaporizado e uma leve espuma",
        preco: 12.9,
        categoria: "cafes",
        tamanho_ml: 300,
        temperatura: "quente",
        cafeina: true,
        opcoes_leite: ["integral", "desnatado", "aveia", "amendoas"],
      },
      {
        id: 103,
        nome: "Chá Verde Async",
        descricao: "Chá verde com hortelã e limão siciliano",
        preco: 9.9,
        categoria: "chas",
        tamanho_ml: 350,
        temperatura: "quente",
        cafeina: true,
      },
      {
        id: 104,
        nome: "Suco Sprint",
        descricao: "Suco natural de laranja, cenoura e gengibre",
        preco: 14.9,
        categoria: "sucos",
        tamanho_ml: 400,
        temperatura: "gelado",
        cafeina: false,
        restricoes: ["vegano", "sem-gluten"],
      },
      {
        id: 105,
        nome: "Smoothie Merge Conflict",
        descricao: "Banana, morango, blueberry e leite de amêndoas",
        preco: 18.9,
        categoria: "smoothies",
        tamanho_ml: 450,
        temperatura: "gelado",
        cafeina: false,
        restricoes: ["vegano", "sem-gluten"],
      },
      {
        id: 106,
        nome: "Água Mineral",
        descricao: "Água mineral sem gás 500ml",
        preco: 5.9,
        categoria: "agua",
        tamanho_ml: 500,
        temperatura: "gelado",
        cafeina: false,
        opcoes: ["com-gas", "sem-gas"],
      },
      {
        id: 107,
        nome: "Refrigerante Zero Bug",
        descricao: "Cola zero açúcar",
        preco: 7.9,
        categoria: "refrigerantes",
        tamanho_ml: 350,
        temperatura: "gelado",
        cafeina: true,
      },
      {
        id: 108,
        nome: "Chopp Git Push",
        descricao: "Chopp artesanal Pilsen bem gelado",
        preco: 15.9,
        categoria: "alcoolicos",
        tamanho_ml: 500,
        temperatura: "gelado",
        cafeina: false,
        teor_alcoolico: "4.8%",
        aviso: "Disponível apenas após 18h",
      },
    ],
  },
  {
    title: "Sobremesas",
    description: "Sobremesas",
    name: "sobremesas",
    resource: "menu://sobremesas",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => [
      {
        id: 201,
        nome: "Petit Gâteau 404",
        descricao:
          "Bolinho de chocolate com centro derretido, sorvete de creme e calda de frutas vermelhas. Não encontrou dieta? Esse é o caminho.",
        preco: 24.9,
        tempo_preparo_minutos: 12,
        calorias: 580,
        restricoes: ["vegetariano"],
        destaque: true,
      },
      {
        id: 202,
        nome: "Brownie Stack Overflow",
        descricao:
          "Brownie quentinho com nozes, coberto de sorvete e calda de chocolate. Generoso demais.",
        preco: 22.9,
        tempo_preparo_minutos: 8,
        calorias: 620,
        restricoes: ["vegetariano"],
        destaque: false,
      },
      {
        id: 203,
        nome: "Pudim de Leite Main Branch",
        descricao:
          "Receita clássica da vó. Cremoso, com calda de caramelo na medida.",
        preco: 14.9,
        tempo_preparo_minutos: 2,
        calorias: 320,
        restricoes: ["vegetariano", "sem-gluten"],
        destaque: false,
      },
      {
        id: 204,
        nome: "Açaí na Nuvem",
        descricao: "Açaí 400ml com granola, banana, morango e leite condensado",
        preco: 26.9,
        tempo_preparo_minutos: 5,
        calorias: 480,
        restricoes: [],
        destaque: true,
        extras_disponiveis: ["mel", "paçoca", "leite ninho", "nutella"],
      },
      {
        id: 205,
        nome: "Sorvete Runtime (2 bolas)",
        descricao:
          "Escolha 2 sabores: chocolate, creme, morango, pistache ou maracujá",
        preco: 16.9,
        tempo_preparo_minutos: 2,
        calorias: 280,
        restricoes: ["vegetariano", "sem-gluten"],
        sabores: ["chocolate", "creme", "morango", "pistache", "maracuja"],
        destaque: false,
      },
      {
        id: 206,
        nome: "Salada de Frutas Low Memory",
        descricao:
          "Mix de frutas frescas da estação com hortelã. Leve e refrescante.",
        preco: 12.9,
        tempo_preparo_minutos: 5,
        calorias: 120,
        restricoes: ["vegano", "sem-gluten"],
        destaque: false,
      },
    ],
  },
  {
    title: "Restrições Alimentares",
    description: "Restrições Alimentares",
    resource: "menu://restricoes-alimentares",
    updated_at: "2025-01-09T11:00:00Z",
    name: "restricoes-alimentares",
    callback: async () => ({
      aviso_legal:
        "Nossos pratos são preparados em cozinha compartilhada. Informe alergias graves ao atendente.",
      categorias: {
        vegano: {
          descricao: "Sem nenhum ingrediente de origem animal",
          icone: "🌱",
          pratos_disponiveis: [
            {
              id: 3,
              nome: "Salada Código Limpo",
              tipo: "prato",
            },
            {
              id: 104,
              nome: "Suco Sprint",
              tipo: "bebida",
            },
            {
              id: 105,
              nome: "Smoothie Merge Conflict",
              tipo: "bebida",
            },
            {
              id: 206,
              nome: "Salada de Frutas Low Memory",
              tipo: "sobremesa",
            },
          ],
        },
        vegetariano: {
          descricao: "Sem carne, mas pode conter ovos e laticínios",
          icone: "🥬",
          pratos_disponiveis: [
            {
              id: 3,
              nome: "Salada Código Limpo",
              tipo: "prato",
            },
            {
              id: 6,
              nome: "Pizza Quatro Commits",
              tipo: "prato",
            },
            {
              id: 7,
              nome: "Risoto Assíncrono",
              tipo: "prato",
            },
            {
              id: 201,
              nome: "Petit Gâteau 404",
              tipo: "sobremesa",
            },
            {
              id: 202,
              nome: "Brownie Stack Overflow",
              tipo: "sobremesa",
            },
            {
              id: 203,
              nome: "Pudim de Leite Main Branch",
              tipo: "sobremesa",
            },
            {
              id: 205,
              nome: "Sorvete Runtime (2 bolas)",
              tipo: "sobremesa",
            },
          ],
        },
        "sem-gluten": {
          descricao: "Livre de glúten - adequado para celíacos",
          icone: "🌾",
          pratos_disponiveis: [
            {
              id: 3,
              nome: "Salada Código Limpo",
              tipo: "prato",
            },
            {
              id: 5,
              nome: "Bowl Serverless",
              tipo: "prato",
            },
            {
              id: 7,
              nome: "Risoto Assíncrono",
              tipo: "prato",
            },
            {
              id: 8,
              nome: "Filé Legacy",
              tipo: "prato",
            },
            {
              id: 104,
              nome: "Suco Sprint",
              tipo: "bebida",
            },
            {
              id: 105,
              nome: "Smoothie Merge Conflict",
              tipo: "bebida",
            },
            {
              id: 203,
              nome: "Pudim de Leite Main Branch",
              tipo: "sobremesa",
            },
            {
              id: 205,
              nome: "Sorvete Runtime (2 bolas)",
              tipo: "sobremesa",
            },
            {
              id: 206,
              nome: "Salada de Frutas Low Memory",
              tipo: "sobremesa",
            },
          ],
        },
        "sem-lactose": {
          descricao: "Livre de lactose",
          icone: "🥛",
          pratos_disponiveis: [
            {
              id: 3,
              nome: "Salada Código Limpo",
              tipo: "prato",
            },
            {
              id: 8,
              nome: "Filé Legacy",
              tipo: "prato",
            },
            {
              id: 104,
              nome: "Suco Sprint",
              tipo: "bebida",
            },
            {
              id: 206,
              nome: "Salada de Frutas Low Memory",
              tipo: "sobremesa",
            },
          ],
          dica: "O Café Latte Refactor pode ser preparado com leite de aveia ou amêndoas",
        },
      },
      alergenos_declarados: [
        "gluten",
        "lactose",
        "amendoim",
        "castanhas",
        "ovos",
        "soja",
        "frutos-do-mar",
      ],
    }),
  },
  {
    title: "Combo do Dia",
    description: "Combo do Dia",
    name: "combo-do-dia",
    resource: "menu://combo-do-dia",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => ({
      validade: "2025-01-09",
      combo: {
        nome: "Sprint Completo",
        descricao: "Prato + Bebida + Sobremesa com desconto especial",
        economia: "15%",
        preco_combo: 52.9,
        preco_separado: 62.7,
        itens: {
          prato: {
            id: 2,
            nome: "Wrap Deploy Rápido",
            preco_individual: 26.9,
          },
          bebida: {
            id: 104,
            nome: "Suco Sprint",
            preco_individual: 14.9,
          },
          sobremesa: {
            id: 203,
            nome: "Pudim de Leite Main Branch",
            preco_individual: 14.9,
          },
        },
        restricoes: ["sem-gluten"],
        disponivel_ate: "15:00",
      },
      frase_do_dia: "Código bom se escreve de barriga cheia 🚀",
    }),
  },
];
