interface Resource {
  name: string;
  title: string;
  description: string;
  resource: string;
  updated_at: string;
  callback: () => Promise<any>;
}

export const resources: Resource[] = [
  {
    name: "meal-to-the-day",
    title: "Meal to the Day",
    description: "Meal to the Day",
    resource: "menu://meal-to-the-day",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => [
      {
        id: 1,
        name: "Cheese Bug-er",
        description:
          "180g beef burger, cheddar cheese, crispy bacon, caramelized onion and our special sauce",
        price: 32.9,
        currency: "USD",
        category: "hamburgueres",
        preparation_time: 15,
        calories: 850,
        restrictions: [],
        popular: true,
      },
      {
        id: 2,
        name: "Quick Deploy Wrap",
        description:
          "Whole grain wrap with grilled chicken, cream cheese, lettuce and tomato slice",
        price: 26.9,
        currency: "USD",
        category: "wraps",
        preparation_time: 8,
        calories: 420,
        restrictions: [],
        popular: false,
      },
      {
        id: 3,
        name: "Clean Code Salad",
        description:
          "Quinoa, mixed greens, roasted sweet potato, cucumber, and tahini dressing",
        price: 28.9,
        currency: "USD",
        category: "saladas",
        preparation_time: 5,
        calories: 320,
        restrictions: ["vegan", "gluten-free"],
        popular: true,
      },
      {
        id: 4,
        name: "Full Stack Pasta",
        description:
          "Spaghetti with tomato sauce, artichoke, and Parmesan cheese",
        price: 34.9,
        currency: "USD",
        category: "massas",
        preparation_time: 18,
        calories: 720,
        restrictions: [],
        popular: false,
      },
      {
        id: 5,
        name: "Serverless Bowl",
        description:
          "Rice bowl with grilled salmon, avocado, edamame, sweet potato and ponzu sauce",
        price: 42.9,
        currency: "USD",
        category: "bowls",
        preparation_time: 12,
        calories: 580,
        restrictions: ["gluten-free"],
        popular: true,
      },
      {
        id: 6,
        name: "Git Commit Pizza",
        description:
          "Pizza with pepperoni, mozzarella, parsley and olives",
        price: 38.9,
        currency: "USD",
        category: "pizzas",
        preparation_time: 20,
        calories: 890,
        restrictions: ["vegetarian"],
        popular: true,
      },
      {
        id: 7,
        name: "Async Risoto",
        description: "Risotto with mushrooms and truffle oil",
        price: 45.9,
        currency: "USD",
        category: "risotos",
        preparation_time: 25,
        calories: 650,
        restrictions: ["vegetarian", "gluten-free"],
        popular: false,
      },
      {
        id: 8,
        name: "Legacy Steak",
        description:
          "Grilled steak with rustic fries and bacon. Classic that never fails.",
        price: 52.9,
        currency: "USD",
        category: "meat",
        preparation_time: 22,
        calories: 980,
        restrictions: ["gluten-free"],
        popular: true,
      },
    ],
  },
  {
    name: "beverages",
    title: "Beverages",
    description: "Beverages",
    resource: "menu://beverages",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => [
      {
        id: 101,
        name: "Debug Coffee",
        description: "Double espresso to solve any problem",
        price: 8.9,
        currency: "USD",
        category: "coffee",
        size_ml: 60,
        temperature: "hot",
        caffeine: true,
      },
      {
        id: 102,
        name: "Latte Refactor",
        description: "Espresso with steamed milk and a light foam",
        price: 12.9,
        currency: "USD",
        category: "coffee",
        size_ml: 300,
        temperature: "hot",
        caffeine: true,
        milk_options: ["whole", "low fat", "oat", "almond"],
      },
      {
        id: 103,
        name: "Evergreen Tea",
        description: "Green tea with hibiscus and Sicilian lime",
        price: 9.9,
        currency: "USD",
        category: "tea",
        size_ml: 350,
        temperature: "hot",
        caffeine: true,
      },
      {
        id: 104,
        name: "Sprint Juice",
        description: "Orange, carrot and ginger natural juice",
        price: 14.9,
        currency: "USD",
        category: "juice",
        size_ml: 400,
        temperature: "cold",
        caffeine: false,
        restrictions: ["vegan", "gluten-free"],
      },
      {
        id: 105,
        name: "Smoothie Merge Conflict",
        description: "Banana, strawberry, blueberry and almond milk",
        price: 18.9,
        currency: "USD",
        category: "smoothies",
        size_ml: 450,
        temperature: "gelado",
        caffeine: false,
        restrictions: ["vegan", "gluten-free"],
      },
      {
        id: 106,
        name: "Minty Water",
        description: "Mineral water with mint",
        price: 5.9,
        category: "agua",
        size_ml: 500,
        temperature: "gelado",
        caffeine: false,
        options: ["sparkling", "flat"],
      },
      {
        id: 107,
        name: "Zero Bug Soda",
        description: "Zero sugar cola",
        price: 7.9,
        category: "refrigerantes",
        size_ml: 350,
        temperature: "gelado",
        caffeine: true,
      },
      {
        id: 108,
        name: "Git Tap",
        description: "Artisanal Pilsen well chilled",
        price: 15.9,
        category: "alcoolicos",
        size_ml: 500,
        temperature: "gelado",
        caffeine: false,
        teor_alcoolico: "4.8%",
        aviso: "Disponível apenas após 18h",
      },
    ],
  },
  {
    title: "Desserts",
    description: "Desserts",
    name: "dessert",
    resource: "menu://dessert",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => [
      {
        id: 201,
        name: "Petit Gâteau 404",
        description:
          "Chocolate pudding with melted center, cream sorbet and red fruit sauce. No diet? This is the way.",
        price: 24.9,
        currency: "USD",
        preparation_time: 12,
        calories: 580,
        restrictions: ["vegetarian"],
        highlight: true,
      },
      {
        id: 202,
        name: "Brownie Stack Overflow",
        description:
          "Brownie with nuts, cream sorbet and chocolate sauce. Generous.",
        price: 22.9,
        currency: "USD",
        preparation_time: 8,
        calories: 620,
        restrictions: ["vegetarian"],
        highlight: false,
      },
      {
        id: 203,
        name: "Main Branch Pudim",
        description:
          "Classic recipe from grandma. Creamy, with caramel sauce.",
        price: 14.9,
        currency: "USD",
        preparation_time: 2,
        calories: 320,
        restrictions: ["vegetarian"],
        highlight: false,
      },
      {
        id: 204,
        name: "Cloud Açaí",
        description: "Açaí 400ml with granola, banana and strawberry",
        price: 26.9,
        currency: "USD",
        preparation_time: 5,
        calories: 480,
        restrictions: [],
        highlight: true,
        extras_available: ["honey", "cacao", "nutella"],
      },
      {
        id: 205,
        name: "Runtime Gelato",
        description:
          "Choose 2 flavors: chocolate, vanilla, strawberry, pistachio or passion fruit",
        price: 16.9,
        currency: "USD",
        preparation_time: 2,
        calories: 280,
        restrictions: ["vegetarian", "gluten-free"],
        flavors: ["chocolate", "vanilla", "strawberry", "pistachio", "passion fruit"],
        highlight: false,
      },
      {
        id: 206,
        name: "Low Memory Fruit Salad",
        description:
          "Mix of fresh fruits from the season with mint. Light and refreshing.",
        price: 12.9,
        currency: "USD",
        preparation_time: 5,
        calories: 120,
        restrictions: ["vegan", "gluten-free"],
        highlight: false,
      },
    ],
  },
  {
    title: "Food Restrictions",
    description: "Food Restrictions",
    resource: "menu://food-restrictions",
    updated_at: "2025-01-09T11:00:00Z",
    name: "food-restrictions",
    callback: async () => ({
      legal_advice:
        "Our dishes are prepared in shared kitchen. Inform severe allergies to the attendant.",
      categories: {
        vegan: {
          description: "Without any animal origin ingredient",
          available_dishes: [
            {
              id: 3,
              name: "Clean Code Salad",
              type: "meal",
            },
            {
              id: 104,
              name: "Sprint Juice",
              type: "beverage",
            },
            {
              id: 105,
              name: "Merge Conflict Smoothie",
              type: "beverage",
            },
            {
              id: 206,
              name: "Low Memory Fruit Salad",
              type: "dessert",
            },
          ],
        },
        vegetarian: {
          description: "Without meat, but may contain eggs and dairy",
          available_dishes: [
            {
              id: 3,
              name: "Clean Code Salad",
              type: "meal",
            },
            {
              id: 6,
              name: "Git Commit Pizza",
              type: "meal",
            },
            {
              id: 7,
              name: "Async Risotto",
              type: "meal",
            },
            {
              id: 201,
              name: "Petit Gâteau 404",
              type: "dessert",
            },
            {
              id: 202,
              name: "Brownie Stack Overflow",
              type: "dessert",
            },
            {
              id: 203,
              name: "Main Branch Pudim",
              type: "dessert",
            },
            {
              id: 205,
              name: "Runtime Gelato",
              type: "dessert",
            },
          ],
        },
        "gluten-free": {
          description: "Without gluten - suitable for celiac",
          icon: "🌾",
          available_dishes: [
            {
              id: 3,
              name: "Clean Code Salad",
              type: "meal",
            },
            {
              id: 5,
              name: "Serverless Bowl",
              type: "meal",
            },
            {
              id: 7,
              name: "Async Risotto",
              type: "meal",
            },
            {
              id: 8,
              name: "Legacy Steak",
              type: "meal",
            },
            {
              id: 104,
              name: "Sprint Juice",
              type: "beverage",
            },
            {
              id: 105,
              name: "Merge Conflict Smoothie",
              type: "beverage",
            },
            {
              id: 203,
              name: "Main Branch Pudim",
              type: "dessert",
            },
            {
              id: 205,
              name: "Runtime Gelato",
              type: "dessert",
            },
            {
              id: 206,
              name: "Low Memory Fruit Salad",
              type: "dessert",
            },
          ],
        },
        "lactose-free": {
          description: "Lactose free",
          icon: "🥛",
          available_dishes: [
            {
              id: 3,
              name: "Clean Code Salad",
              type: "meal",
            },
            {
              id: 8,
              name: "Legacy Steak",
              type: "meal",
            },
            {
              id: 104,
              name: "Sprint Juice",
              type: "beverage",
            },
            {
              id: 206,
              name: "Low Memory Fruit Salad",
              type: "dessert",
            },
          ],
          tip: "The Latte Refactor can be prepared with oat milk or almonds",
        },
      },
      declared_allergens: [
        "gluten",
        "lactose",
        "peanuts",
        "cashews",
        "eggs",
        "soy",
        "seafood",
      ],
    }),
  },
  {
    title: "Daily Combo",
    description: "Daily Combo",
    name: "daily-combo",
    resource: "menu://daily-combo",
    updated_at: "2025-01-09T11:00:00Z",
    callback: async () => ({
      valid_until: "2025-01-09",
      combo: {
        name: "Standup Daily Combo",
        description: "Dishe + Beverage + Dessert with special discount",
        save: "15%",
        price_combo: 52.9,
        price_separated: 62.7,
        itens: {
          dishe: {
            id: 2,
            name: "Quick deploy Wrap",
            price_individual: 26.9,
          },
          beverage: {
            id: 104,
            name: "Sprint Juice",
            price_individual: 14.9,
          },
          dessert: {
            id: 203,
            name: "Main Branch Pudim",
            price_individual: 14.9,
          },
        },
        restrictions: ["gluten-free"],
        available_until: "15:00",
      },
      daily_quote: "Good code is written with no hunger 🚀",
    }),
  },
];
